version: "3.9"

services:
  task-app:
    image: task-system
    container_name: task-app
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - SECRET_KEY=4b65792d4d7573742d42652d61742d6c656173742d33322d62797465732d696e2d6c656e67746821
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
