create table users
(
    id       bigint generated by default as identity
        primary key,
    name     varchar(30)  not null,
    email    varchar(50)  not null
        unique,
    password varchar(255) not null
);

alter table users
    owner to postgres;

create table status
(
    id   integer generated by default as identity
        primary key,
    name varchar(30) not null
);

alter table status
    owner to postgres;

create table priority
(
    id   integer generated by default as identity
        primary key,
    name varchar(30) not null
);

alter table priority
    owner to postgres;

create table task
(
    id          bigint generated by default as identity
        primary key,
    title       varchar(30)     not null,
    description varchar(100000) not null,
    status_id   integer         not null
        constraint task_status_id_fk
            references status,
    priority_id integer         not null
        constraint task_priority_id_fk
            references priority,
    author_id   bigint          not null
        constraint task_author_id_fk
            references users,
    executor_id bigint          not null
        constraint task_executor_id_fk
            references users
);

alter table task
    owner to postgres;

create table comment
(
    id          bigint generated by default as identity
        primary key,
    description varchar(100000) not null,
    task_id     integer         not null
        constraint comment_task_id_fk
            references task,
    author_id   bigint          not null
        constraint comment_author_id_fk
            references users
);

alter table comment
    owner to postgres;

insert into priority (name)
VALUES ('High'),
        ('Medium'),
        ('Low');

insert into status (name)
VALUES ('In process'),
       ('Wait'),
       ('Complete'),
       ('Cancel');

